FROM node:14.15.4-slim

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node package*.json ./

RUN npm install

COPY --chown=node ./ .

EXPOSE 3049

CMD ["npm", "run", "start"]